backend:
  name: git-gateway
  branch: main

media_folder: "assets/img/products"
public_folder: "/assets/img/products"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Handbags", "Perfumes"]}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}